"""Company templates: builtin (ScopeAI design), sample (neutral company sample generated by code)
and custom (file uploaded on the Settings page, validated before it replaces anything)."""

import io
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from app.company import load_case_studies, load_company, load_content_blocks
from app.knowledge import loader
from app.schemas.settings import (
    CaseStudy,
    CompanyProfile,
    ContentBlock,
    TemplateKind,
    TemplatesConfig,
    TemplateSource,
)

CONFIG_FILE = "templates.yaml"
FILES: dict[str, str] = {
    "slides": "slides.pptx",
    "proposal_docx": "proposal.docx",
    "workbook": "workbook.xlsx",
    "qa_sheet": "qa_sheet.xlsx",
}
MAX_TEMPLATE_BYTES = 10 * 1024 * 1024
HEADER = "# Sửa từ trang Cài đặt → Template của ScopeAI.\n"


class TemplateError(ValueError):
    pass


def _kb(kb_dir: Path | None) -> Path:
    return kb_dir or loader.KB_DIR


def load_templates_config(kb_dir: Path | None = None) -> TemplatesConfig:
    return TemplatesConfig.model_validate(loader.load_yaml(CONFIG_FILE, _kb(kb_dir)))


def save_templates_config(cfg: TemplatesConfig, kb_dir: Path | None = None) -> TemplatesConfig:
    text = yaml.safe_dump(cfg.model_dump(mode="json"), allow_unicode=True, sort_keys=False)
    (_kb(kb_dir) / CONFIG_FILE).write_text(HEADER + text, encoding="utf-8")
    return cfg


def template_path(kind: str, source: str, kb_dir: Path | None = None) -> Path:
    return _kb(kb_dir) / "templates" / source / FILES[kind]


def ensure_samples(kb_dir: Path | None = None) -> None:
    """Sample templates are generated by code (no real company branding); rebuilt if missing."""
    missing = [k for k in FILES if not template_path(k, "sample", kb_dir).exists()]
    if missing:
        from app.exports.sample_templates import build_sample_templates

        build_sample_templates(_kb(kb_dir) / "templates" / "sample")


def resolve(kind: str, source: str, kb_dir: Path | None = None) -> Path | None:
    if source == "builtin":
        return None
    if source == "sample":
        ensure_samples(kb_dir)
    path = template_path(kind, source, kb_dir)
    return path if path.exists() else None


@dataclass
class ExportKit:
    """Everything company-specific an export needs, loaded once per export."""

    company: CompanyProfile
    blocks: list[ContentBlock]
    case_studies: list[CaseStudy]
    config: TemplatesConfig
    templates: dict[str, Path | None]

    @classmethod
    def load(cls, kb_dir: Path | None = None, source: TemplateSource | None = None) -> "ExportKit":
        """source=None uses the active template per document; otherwise forces one source."""
        cfg = load_templates_config(kb_dir)
        templates = {kind: resolve(kind, source or cfg.active[kind], kb_dir) for kind in FILES}  # type: ignore[index]
        return cls(
            load_company(kb_dir),
            load_content_blocks(kb_dir),
            load_case_studies(kb_dir),
            cfg,
            templates,
        )


# ---------- listing / upload ----------
def list_templates(kb_dir: Path | None = None) -> dict[str, Any]:
    ensure_samples(kb_dir)
    cfg = load_templates_config(kb_dir)
    items = []
    for kind, filename in FILES.items():
        custom = template_path(kind, "custom", kb_dir)
        stat = custom.stat() if custom.exists() else None
        items.append(
            {
                "kind": kind,
                "filename": filename,
                "active": cfg.active[kind],  # type: ignore[index]
                "sample": True,
                "custom": (
                    {
                        "size": stat.st_size,
                        "uploaded_at": datetime.fromtimestamp(stat.st_mtime, UTC).isoformat(),
                    }
                    if stat
                    else None
                ),
            }
        )
    return {"items": items, "config": cfg.model_dump(mode="json")}


def _check_pptx(data: bytes, cfg: TemplatesConfig) -> list[str]:
    from pptx import Presentation

    from app.exports.templating import CONTENT_MARKER, _title_placeholder, find_layouts

    try:
        prs = Presentation(io.BytesIO(data))
    except Exception as exc:
        raise TemplateError("File không phải PowerPoint (.pptx) hợp lệ.") from exc
    if not len(prs.slide_layouts):
        raise TemplateError("Template không có layout nào trong Slide Master.")
    warnings = []
    name = str(cfg.pptx.get("content_layout") or "")
    names = [lo.name for lo in prs.slide_layouts]
    cover, content = find_layouts(prs, name or None)
    if name and name not in names:
        warnings.append(
            f"Không có layout '{name}', sẽ dùng '{content.name}'. Các layout: {', '.join(names)}."
        )
    if _title_placeholder(content) is None:
        warnings.append(
            f"Layout '{content.name}' không có ô tiêu đề; tiêu đề slide sẽ vẽ bằng text box."
        )
    has_marker = any(
        shape.has_text_frame and shape.text_frame.text.strip() == CONTENT_MARKER
        for lo in prs.slide_layouts
        for shape in lo.shapes
    )
    if not has_marker:
        warnings.append(
            "Không có ô {{SCOPEAI_CONTENT}}: vùng nội dung tính tự động từ vị trí tiêu đề."
        )
    return warnings


def _check_docx(data: bytes) -> list[str]:
    from docx import Document

    from app.exports.templating import find_body_marker

    try:
        doc = Document(io.BytesIO(data))
    except Exception as exc:
        raise TemplateError("File không phải Word (.docx) hợp lệ.") from exc
    warnings = []
    if find_body_marker(doc) is None:
        warnings.append(
            "Không có đoạn {{SCOPEAI_BODY}}: nội dung proposal sẽ nối vào cuối tài liệu."
        )
    styles = {s.name for s in doc.styles}
    missing = [
        s for s in ("Heading 1", "Heading 2", "List Bullet", "Table Grid") if s not in styles
    ]
    if missing:
        warnings.append(f"Thiếu style {', '.join(missing)}: sẽ dùng định dạng thường thay thế.")
    return warnings


def _check_xlsx(data: bytes, sheets: list[str]) -> list[str]:
    from openpyxl import load_workbook

    try:
        wb = load_workbook(io.BytesIO(data))
    except Exception as exc:
        raise TemplateError("File không phải Excel (.xlsx) hợp lệ.") from exc
    missing = [s for s in sheets if s not in wb.sheetnames]
    return [
        f"Không có sheet '{s}' theo cấu hình cột; ScopeAI sẽ tự tạo sheet này." for s in missing
    ]


def validate_template(kind: str, data: bytes, cfg: TemplatesConfig) -> list[str]:
    if kind not in FILES:
        raise TemplateError("Loại template không hợp lệ.")
    if len(data) > MAX_TEMPLATE_BYTES:
        raise TemplateError("Template tối đa 10 MB.")
    if kind == "slides":
        return _check_pptx(data, cfg)
    if kind == "proposal_docx":
        return _check_docx(data)
    if kind == "workbook":
        return _check_xlsx(data, [cfg.workbook["wbs"].sheet, cfg.workbook["pricing"].sheet])
    return _check_xlsx(data, [cfg.qa_sheet.sheet])


def save_custom(kind: str, filename: str, data: bytes, kb_dir: Path | None = None) -> list[str]:
    expected = FILES.get(kind, "")
    if not re.search(rf"\.{expected.rsplit('.', 1)[-1]}$", filename.lower()):
        raise TemplateError(f"Template này cần file {expected.rsplit('.', 1)[-1]}.")
    cfg = load_templates_config(kb_dir)
    warnings = validate_template(kind, data, cfg)
    path = template_path(kind, "custom", kb_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    cfg.active[kind] = "custom"  # type: ignore[index]
    save_templates_config(cfg, kb_dir)
    return warnings


def delete_custom(kind: str, kb_dir: Path | None = None) -> bool:
    path = template_path(kind, "custom", kb_dir) if kind in FILES else None
    if path is None or not path.exists():
        return False
    path.unlink()
    cfg = load_templates_config(kb_dir)
    if cfg.active[kind] == "custom":  # type: ignore[index]
        cfg.active[kind] = "sample"  # type: ignore[index]
        save_templates_config(cfg, kb_dir)
    return True


def set_active(
    kind: TemplateKind, source: TemplateSource, kb_dir: Path | None = None
) -> TemplatesConfig:
    if source == "custom" and not template_path(kind, "custom", kb_dir).exists():
        raise TemplateError("Chưa upload template riêng cho loại này.")
    cfg = load_templates_config(kb_dir)
    cfg.active[kind] = source
    return save_templates_config(cfg, kb_dir)
