"""Neutral sample company templates ("Công ty ABC (mẫu)"), generated by code.

They show how a real company template plugs in (placeholders, content markers, sheet mappings)
without using any real brand. Run `python -m app.exports.sample_templates` to rebuild them."""

import copy
import io
from pathlib import Path

from docx import Document
from docx.enum.text import WD_BREAK
from docx.oxml import OxmlElement
from docx.oxml.ns import qn as wqn
from docx.shared import Cm, Pt, RGBColor
from lxml import etree
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from pptx import Presentation
from pptx.dml.color import RGBColor as PptxRGB
from pptx.enum.dml import MSO_LINE_DASH_STYLE
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.opc.constants import RELATIONSHIP_TYPE as RT
from pptx.oxml.ns import qn
from pptx.util import Inches
from pptx.util import Pt as PPt

from app.config import BACKEND_DIR
from app.exports.templating import BODY_MARKER, CONTENT_MARKER

BRAND = "0B5CAD"  # sample brand blue
NAVY = "0F1B3D"
MUTED = "6B7280"
SAMPLE_DIR = BACKEND_DIR / "knowledge_base" / "templates" / "sample"


# ---------- PowerPoint ----------
def _xml_set_theme(prs: Presentation) -> None:
    theme = prs.slide_master.part.part_related_by(RT.THEME)
    root = etree.fromstring(theme.blob)
    a = "{http://schemas.openxmlformats.org/drawingml/2006/main}"
    for name, value in (("accent1", BRAND), ("dk2", NAVY), ("accent2", "14B8A6")):
        node = root.find(f".//{a}{name}")
        if node is not None:
            for child in list(node):
                node.remove(child)
            etree.SubElement(node, f"{a}srgbClr", val=value)
    for font in root.iter(f"{a}latin"):
        if font.getparent().tag in (f"{a}majorFont", f"{a}minorFont"):
            font.set("typeface", "Arial")
    theme._blob = etree.tostring(root, xml_declaration=True, encoding="UTF-8", standalone=True)


def _scale_x(element, factor: float) -> None:
    """Stretch explicit placeholder positions from the 4:3 default to 16:9."""
    for xfrm in element.iter(qn("a:xfrm")):
        off, ext = xfrm.find(qn("a:off")), xfrm.find(qn("a:ext"))
        if off is not None:
            off.set("x", str(int(int(off.get("x")) * factor)))
        if ext is not None:
            ext.set("cx", str(int(int(ext.get("cx")) * factor)))


def _place(shape, x: float, y: float, w: float, h: float) -> None:
    shape.left, shape.top, shape.width, shape.height = Inches(x), Inches(y), Inches(w), Inches(h)


def _list_style(ph, size: int, color: str, bold: bool = False, align: str = "l") -> None:
    body = ph.text_frame._txBody
    old = body.find(qn("a:lstStyle"))
    style = etree.SubElement(body, qn("a:lstStyle"))
    if old is not None:
        old.addprevious(style)
        body.remove(old)
    else:
        body.find(qn("a:bodyPr")).addnext(style)
    lvl = etree.SubElement(style, qn("a:lvl1pPr"), algn=align)
    etree.SubElement(lvl, qn("a:buNone"))
    rpr = etree.SubElement(lvl, qn("a:defRPr"), sz=str(size * 100), b="1" if bold else "0")
    fill = etree.SubElement(rpr, qn("a:solidFill"))
    etree.SubElement(fill, qn("a:srgbClr"), val=color)


def _shape(container, kind, x, y, w, h, fill: str | None, text: str = "", size: int = 10,
           color: str = "FFFFFF", bold: bool = False, align=PP_ALIGN.LEFT):  # fmt: skip
    """Add a shape to a slide, then the caller moves its element into a master/layout tree."""
    shape = container.shapes.add_shape(kind, Inches(x), Inches(y), Inches(w), Inches(h))
    if fill:
        shape.fill.solid()
        shape.fill.fore_color.rgb = PptxRGB.from_string(fill)
    else:
        shape.fill.background()
    shape.line.fill.background()
    shape.shadow.inherit = False
    if text:
        frame = shape.text_frame
        frame.word_wrap = True
        frame.vertical_anchor = MSO_ANCHOR.MIDDLE
        frame.margin_left = frame.margin_right = Inches(0.08)
        p = frame.paragraphs[0]
        p.alignment = align
        run = p.add_run()
        run.text = text
        run.font.size, run.font.bold = PPt(size), bold
        run.font.color.rgb = PptxRGB.from_string(color)
    return shape


def _move(shape, tree, at_start: bool = False) -> None:
    el = shape.element
    el.getparent().remove(el)
    if at_start:
        tree.insert(2, el)  # after nvGrpSpPr and grpSpPr: behind the placeholders
    else:
        tree.append(el)


def build_sample_pptx() -> bytes:
    prs = Presentation()
    factor = 13.333 / 10
    prs.slide_width, prs.slide_height = Inches(13.333), Inches(7.5)
    _xml_set_theme(prs)
    master = prs.slide_master
    _scale_x(master.element, factor)
    for layout in prs.slide_layouts:
        _scale_x(layout.element, factor)

    # master: title style, brand bar, logo, footer line and text, slide number
    title_lvl = master.element.find(qn("p:txStyles")).find(qn("p:titleStyle")).find(qn("a:lvl1pPr"))
    title_lvl.set("algn", "l")
    rpr = title_lvl.find(qn("a:defRPr"))
    rpr.set("sz", "2600")
    rpr.set("b", "1")
    fill = rpr.find(qn("a:solidFill"))
    for child in list(fill):
        fill.remove(child)
    etree.SubElement(fill, qn("a:srgbClr"), val=NAVY)
    for ph in master.placeholders:
        kind = ph.placeholder_format.idx
        if kind == 0:
            _place(ph, 0.5, 0.32, 11.0, 0.85)
            ph.text_frame._txBody.find(qn("a:bodyPr")).set("anchor", "ctr")
        elif kind == 1:
            _place(ph, 0.6, 1.4, 12.1, 5.3)
        elif kind == 2:
            ph.element.getparent().remove(ph.element)
        elif kind == 3:
            _place(ph, 0.5, 7.02, 9.0, 0.32)
        elif kind == 4:
            _place(ph, 11.9, 7.02, 0.95, 0.32)
            _list_style(ph, 9, MUTED, align="r")

    scratch = prs.slides.add_slide(prs.slide_layouts[6])
    tree = master.shapes._spTree
    _move(_shape(scratch, MSO_SHAPE.RECTANGLE, 0, 0, 13.333, 0.08, BRAND), tree)
    # logo cards: {{company_logo}} becomes the uploaded logo, or the short name without one
    logo = _shape(scratch, MSO_SHAPE.ROUNDED_RECTANGLE, 11.55, 0.42, 1.3, 0.6, "FFFFFF", "{{company_logo}}",
                  14, NAVY, bold=True, align=PP_ALIGN.CENTER)  # fmt: skip
    logo.line.color.rgb = PptxRGB.from_string("D1D5DB")
    _move(logo, tree)
    _move(_shape(scratch, MSO_SHAPE.RECTANGLE, 0.5, 6.95, 12.333, 0.012, "D1D5DB"), tree)
    _move(_shape(scratch, MSO_SHAPE.RECTANGLE, 0.5, 7.02, 9.5, 0.32, None,
                 "{{company_name}} · {{confidential_footer}}", 9, MUTED), tree)  # fmt: skip

    # cover layout: full-bleed navy, master graphics hidden
    cover = prs.slide_layouts[0]
    cover.element.set("showMasterSp", "0")
    ctree = cover.shapes._spTree
    _move(_shape(scratch, MSO_SHAPE.RECTANGLE, 0, 0, 13.333, 7.5, NAVY), ctree, at_start=True)
    _move(_shape(scratch, MSO_SHAPE.RECTANGLE, 0.9, 2.05, 0.12, 2.9, BRAND), ctree)
    _move(_shape(scratch, MSO_SHAPE.ROUNDED_RECTANGLE, 0.9, 0.6, 2.2, 0.8, "FFFFFF", "{{company_logo}}",
                 16, NAVY, bold=True, align=PP_ALIGN.CENTER), ctree)  # fmt: skip
    _move(_shape(scratch, MSO_SHAPE.RECTANGLE, 0.9, 6.3, 9, 0.36, None, "{{company_name}}", 13,
                 "FFFFFF", bold=True), ctree)  # fmt: skip
    _move(_shape(scratch, MSO_SHAPE.RECTANGLE, 0.9, 6.65, 11, 0.32, None, "{{confidential_footer}}", 10,
                 "9CA3AF"), ctree)  # fmt: skip
    for ph in list(cover.placeholders):
        kind = ph.placeholder_format.idx
        if kind == 0:
            _place(ph, 1.25, 1.95, 11.2, 1.7)
            _list_style(ph, 34, "FFFFFF", bold=True)
            ph.text_frame._txBody.find(qn("a:bodyPr")).set("anchor", "b")
        elif kind == 1:
            _place(ph, 1.27, 3.8, 10.8, 1.3)
            _list_style(ph, 16, "C7D2FE")
            ph.text_frame._txBody.find(qn("a:bodyPr")).set("anchor", "t")
        else:
            ph.element.getparent().remove(ph.element)

    # content layout: title + marker box for the ScopeAI content area
    content = prs.slide_layouts[5]
    marker = _shape(scratch, MSO_SHAPE.RECTANGLE, 0.6, 1.35, 12.1, 5.45, None, CONTENT_MARKER, 12, "9CA3AF",
                    align=PP_ALIGN.CENTER)  # fmt: skip
    marker.line.color.rgb = PptxRGB.from_string("D1D5DB")
    marker.line.dash_style = MSO_LINE_DASH_STYLE.DASH
    _move(marker, content.shapes._spTree)
    for ph in list(content.placeholders):
        if ph.placeholder_format.idx == 10:
            ph.element.getparent().remove(ph.element)

    # remove the scratch slide, then add two example slides so the file shows the design
    from app.exports.templating import drop_slides

    drop_slides(prs)
    example = prs.slides.add_slide(cover)
    example.shapes.title.text = "{{proposal_title}}"
    example.placeholders[1].text = "Mục tiêu của khách hàng\n{{client_name}} · {{date}}"
    page = prs.slides.add_slide(content)
    page.shapes.title.text = "Tiêu đề slide nội dung"
    for ph in content.placeholders:
        if ph.placeholder_format.idx in (11, 12):
            page.shapes._spTree.append(copy.deepcopy(ph.element))
    buffer = io.BytesIO()
    prs.save(buffer)
    return buffer.getvalue()


# ---------- Word ----------
def _field(paragraph, instr: str) -> None:
    fld = OxmlElement("w:fldSimple")
    fld.set(wqn("w:instr"), instr)
    run = OxmlElement("w:r")
    text = OxmlElement("w:t")
    text.text = "1"
    run.append(text)
    fld.append(run)
    paragraph._p.append(fld)


def _bottom_border(paragraph, color: str) -> None:
    ppr = paragraph._p.get_or_add_pPr()
    borders = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    for key, value in (("val", "single"), ("sz", "6"), ("space", "4"), ("color", color)):
        bottom.set(wqn(f"w:{key}"), value)
    borders.append(bottom)
    ppr.append(borders)


def build_sample_docx() -> bytes:
    doc = Document()
    normal = doc.styles["Normal"]
    normal.font.name, normal.font.size = "Arial", Pt(10.5)
    rpr = normal.element.get_or_add_rPr()
    fonts = rpr.find(wqn("w:rFonts"))
    if fonts is None:
        fonts = OxmlElement("w:rFonts")
        rpr.append(fonts)
    fonts.set(wqn("w:eastAsia"), "Yu Gothic")
    for level, (size, color) in {1: (16, BRAND), 2: (13, NAVY), 3: (11, NAVY)}.items():
        style = doc.styles[f"Heading {level}"]
        style.font.name, style.font.size = "Arial", Pt(size)
        style.font.color.rgb = RGBColor.from_string(color)
    section = doc.sections[0]
    section.left_margin = section.right_margin = Cm(2.2)
    section.different_first_page_header_footer = True

    header = section.header.paragraphs[0]
    run = header.add_run("{{company_logo}}")
    run.bold, run.font.color.rgb = True, RGBColor.from_string(BRAND)
    header.add_run("   |   {{proposal_title}}").font.color.rgb = RGBColor.from_string(MUTED)
    _bottom_border(header, "D1D5DB")
    footer = section.footer.paragraphs[0]
    footer.add_run("{{confidential_footer}}   ·   Trang ").font.size = Pt(8)
    _field(footer, "PAGE")

    # cover page
    for _ in range(5):
        doc.add_paragraph()
    brand = doc.add_paragraph()
    run = brand.add_run("{{company_name}}")
    run.bold, run.font.size, run.font.color.rgb = True, Pt(13), RGBColor.from_string(BRAND)
    title = doc.add_paragraph()
    run = title.add_run("{{proposal_title}}")
    run.bold, run.font.size, run.font.color.rgb = True, Pt(26), RGBColor.from_string(NAVY)
    _bottom_border(title, BRAND)
    for text in (
        "Kính gửi: {{client_name}}",
        "Dự án: {{project_name}}",
        "Phiên bản {{version}} · {{date}}",
    ):
        p = doc.add_paragraph()
        p.add_run(text).font.size = Pt(12)
    doc.add_paragraph().add_run().add_break(WD_BREAK.PAGE)
    doc.add_paragraph(BODY_MARKER)
    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


# ---------- Excel ----------
THIN = Side(style="thin", color="D1D5DB")
BOX = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
HEAD_FILL = PatternFill("solid", fgColor=BRAND)


def _sheet_head(
    ws, title: str, headers: list[tuple[str, int]], total: tuple[str, str] | None = None
) -> None:
    ws["A1"] = title
    ws["A1"].font = Font(bold=True, size=14, color=NAVY)
    ws["A2"] = "{{company_name}} · Dự án: {{project_name}} · Khách hàng: {{client_name}} · {{date}}"
    ws["A2"].font = Font(color=MUTED)
    if total:
        ws["D3"], ws["E3"] = total
        ws["D3"].font = Font(bold=True)
        ws["E3"].font = Font(bold=True, color=BRAND)
        ws["E3"].number_format = "#,##0"
    for col, (name, width) in enumerate(headers, start=1):
        cell = ws.cell(row=5, column=col, value=name)
        cell.fill, cell.font, cell.border = HEAD_FILL, Font(bold=True, color="FFFFFF"), BOX
        cell.alignment = Alignment(vertical="center", wrap_text=True)
        ws.column_dimensions[cell.column_letter].width = width
    ws.freeze_panes = "A6"


def build_sample_workbook() -> bytes:
    wb = Workbook()
    cover = wb.active
    cover.title = "Cover"
    cover["A1"] = "{{company_name}}"
    cover["A1"].font = Font(bold=True, size=12, color=BRAND)
    cover["A3"] = "BẢNG ƯỚC TÍNH & BÁO GIÁ"
    cover["A3"].font = Font(bold=True, size=18, color=NAVY)
    for row, text in enumerate(
        ("Dự án: {{project_name}}", "Khách hàng: {{client_name}}", "Phiên bản: {{version}} · Ngày: {{date}}",
         "{{confidential_footer}}"), start=5):  # fmt: skip
        cover.cell(row=row, column=1, value=text)
    cover.column_dimensions["A"].width = 70
    wbs = wb.create_sheet("WBS")
    _sheet_head(
        wbs,
        "WBS – {{project_name}}",
        [
            ("ID", 8),
            ("Giai đoạn", 13),
            ("Đầu việc", 48),
            ("Vai trò", 22),
            ("Ngày công", 11),
            ("Tuần bắt đầu", 13),
            ("Tuần kết thúc", 13),
        ],  # fmt: skip
        ("Tổng ngày công", "=SUM(E6:E500)"),
    )
    pricing = wb.create_sheet("Pricing")
    _sheet_head(
        pricing,
        "Báo giá – {{project_name}} (chưa gồm VAT)",
        [
            ("Giai đoạn", 14),
            ("Vai trò", 26),
            ("Ngày công", 11),
            ("Đơn giá / ngày", 16),
            ("Thành tiền", 18),
        ],
        ("Tổng chi phí nhân sự", "=SUM(E6:E500)"),
    )
    buffer = io.BytesIO()
    wb.save(buffer)
    return buffer.getvalue()


def build_sample_qa_sheet() -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Q&A"
    _sheet_head(
        ws,
        "DANH SÁCH CÂU HỎI LÀM RÕ – {{project_name}}",
        [
            ("ID", 7),
            ("STT", 6),
            ("Chủ đề", 16),
            ("Câu hỏi", 60),
            ("Bắt buộc", 10),
            ("Câu trả lời", 50),
        ],
    )
    ws["A3"] = "Vui lòng điền cột Câu trả lời và gửi lại file. Không sửa cột ID."
    ws["A3"].font = Font(italic=True, color=MUTED)
    buffer = io.BytesIO()
    wb.save(buffer)
    return buffer.getvalue()


def build_sample_templates(directory: Path = SAMPLE_DIR) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "slides.pptx").write_bytes(build_sample_pptx())
    (directory / "proposal.docx").write_bytes(build_sample_docx())
    (directory / "workbook.xlsx").write_bytes(build_sample_workbook())
    (directory / "qa_sheet.xlsx").write_bytes(build_sample_qa_sheet())


if __name__ == "__main__":
    build_sample_templates()
    print(f"Sample templates written to {SAMPLE_DIR}")
